const path = require('node:path');
const utils = require('../utils');

/**
 * Format results using the "inspections" style. ESLint messages are grouped by rule.
 * @param {array} results The output generated by running ESLint.
 * @param {object} config The settings to be used by the formatter.
 * @returns {array} The final list of messages to be displayed in TeamCity
 */
module.exports = (results, config) => {
  const { reportName } = config;
  let errorCount = 0;
  let warningCount = 0;

  const inspectionMessages = results.flatMap((result) => {
    const { messages } = result;

    if (messages.length === 0) {
      return [];
    }

    const relativeFilePath = path.relative(process.cwd(), result.filePath);
    const filePath = utils.escapeTeamCityString(relativeFilePath.replace(/\\/g, '/')); // Ensure slashes on Windows

    return messages.flatMap((messageObj) => {
      const { line, column, message, ruleId, fatal, severity } = messageObj;
      const isError = fatal || severity === 2;

      if (isError) {
        errorCount += 1;
      } else {
        warningCount += 1;
      }

      const escapedRuleId = utils.escapeTeamCityString(ruleId || '<none>');
      const escapedMessage = utils.escapeTeamCityString(message);
      const formattedMessage = `line ${line}, col ${column}, ${escapedMessage}`;
      const severityLevel = isError ? 'ERROR' : 'WARNING';

      return [
        `##teamcity[inspectionType id='${escapedRuleId}' category='${reportName}' name='${escapedRuleId}' description='${reportName}']`,
        `##teamcity[inspection typeId='${escapedRuleId}' message='${formattedMessage}' file='${filePath}' line='${line}' SEVERITY='${severityLevel}']`,
      ];
    });
  });

  return [
    ...inspectionMessages,
    `##teamcity[buildStatisticValue key='${config.errorStatisticsName}' value='${errorCount}']`,
    `##teamcity[buildStatisticValue key='${config.warningStatisticsName}' value='${warningCount}']`,
  ];
};
