const utils = require('./utils');
const formatErrors = require('./formatters/errors');
const formatInspections = require('./formatters/inspections');

const formatters = {
  inspections: formatInspections,
  errors: formatErrors,
};

/**
 * Resolve a single config value using the priority chain:
 * prop → package.json → env → default
 */
function resolveConfigValue(prop, packageJsonValue, envVar, defaultValue) {
  return prop || packageJsonValue || process.env[envVar] || defaultValue;
}

/**
 * Determines the config to be used by the respective formatter
 * Config is selected based on the following priority:
 *    1. Any user defined props when running eslint-formatter-teamcity
 *    2. package.json settings
 *    3. ENV variables
 *    4. Default value
 * @param {object} propNames Optional config variables that will override all other config settings
 * @returns {object} The final config settings to be used
 */
function getUserConfig(propNames) {
  // Attempt to load package.json from current directory
  const config = JSON.parse(utils.loadPackageJson())['eslint-formatter-teamcity'] || {};

  const reporter = resolveConfigValue(
    propNames.reporter, config.reporter, 'ESLINT_TEAMCITY_REPORTER', 'errors'
  );
  const reportName = resolveConfigValue(
    propNames.reportName, config['report-name'], 'ESLINT_TEAMCITY_REPORT_NAME', 'ESLint Violations'
  );
  const errorStatisticsName = resolveConfigValue(
    propNames.errorStatisticsName, config['error-statistics-name'], 'ESLINT_TEAMCITY_ERROR_STATISTICS_NAME', 'ESLint Error Count'
  );
  const warningStatisticsName = resolveConfigValue(
    propNames.warningStatisticsName, config['warning-statistics-name'], 'ESLINT_TEAMCITY_WARNING_STATISTICS_NAME', 'ESLint Warning Count'
  );

  return {
    reporter,
    reportName: utils.escapeTeamCityString(reportName),
    errorStatisticsName: utils.escapeTeamCityString(errorStatisticsName),
    warningStatisticsName: utils.escapeTeamCityString(warningStatisticsName),
  };
}

/**
 * Determines the formatter to use and any config variables to use
 * @param {array} results The output generated by running ESLint.
 * @param {object} [propNames] Optional config variables that will override all other
 * config settings
 * @returns {string} The concatenated output of all messages to display in TeamCity
 */
function getTeamCityOutput(results, propNames = {}) {
  const config = getUserConfig(propNames);

  if (process.env.ESLINT_TEAMCITY_DISPLAY_CONFIG) {
    console.info(`Running ESLint Teamcity with config: ${JSON.stringify(config, null, 4)}`);
  }

  const format = formatters[config.reporter.toLowerCase()] || formatErrors;
  const outputMessages = format(results, config);

  return outputMessages.join('\n');
}

module.exports = getTeamCityOutput;
